// One-time migration snapshot from the legacy Next.js menu.
// Do not edit manually: all 215 original menu item and variant entries are preserved.

export const legacyMenuEntries = [
  {
    category: "starters",
    description:
      "CHAUSSON DE VIANDE POULET OU BOEUF, PETITS POIS ET POMMES DE TERRE",
    kind: "item",
    name: "SAMOSSA VIANDE - 2P",
    priceCents: 500,
    sourceOrder: 0,
  },
  {
    category: "starters",
    description: "CHAUSSON DE LÉGUMES ET POMME DE TERRE",
    kind: "item",
    name: "SAMOSSA LÉGUMES - 2P",
    priceCents: 500,
    sourceOrder: 1,
  },
  {
    category: "starters",
    description: "ROULEAUX PANÉS DE VIANDE ET POMME DE TERRE",
    kind: "item",
    name: "ROLLS VIANDE - 2P",
    priceCents: 500,
    sourceOrder: 2,
  },
  {
    category: "starters",
    description: "BEIGNETS À LA FARINE DE POIS CHICHE",
    kind: "item",
    name: "BADJI",
    priceCents: null,
    sourceOrder: 3,
  },
  {
    category: "starters",
    description: "",
    kind: "variant",
    name: "BADJI AUX AUBERGINES - 3P",
    priceCents: 500,
    sourceOrder: 4,
  },
  {
    category: "starters",
    description: "",
    kind: "variant",
    name: "BADJI AUX POMMES DE TERRE",
    priceCents: 500,
    sourceOrder: 5,
  },
  {
    category: "starters",
    description: "",
    kind: "variant",
    name: "BADJI AUX OIGNONS - 3P",
    priceCents: 500,
    sourceOrder: 6,
  },
  {
    category: "starters",
    description: "",
    kind: "variant",
    name: "BADJI AUX CREVETTES - 3P",
    priceCents: 750,
    sourceOrder: 7,
  },
  {
    category: "starters",
    description: "",
    kind: "variant",
    name: "ASSORTISSEMENTS POUR 2 PERSONNES",
    priceCents: 900,
    sourceOrder: 8,
  },
  {
    category: "starters",
    description: "BEIGNET AUX LENTILLES",
    kind: "item",
    name: "VADAI",
    priceCents: null,
    sourceOrder: 9,
  },
  {
    category: "starters",
    description: "",
    kind: "variant",
    name: "VADA - 2P",
    priceCents: 400,
    sourceOrder: 10,
  },
  {
    category: "starters",
    description: "",
    kind: "variant",
    name: "VADA AUX EPINARDS - 1P",
    priceCents: 400,
    sourceOrder: 11,
  },
  {
    category: "starters",
    description: "",
    kind: "variant",
    name: "SAMBAR VADAI - 2P",
    priceCents: 450,
    sourceOrder: 12,
  },
  {
    category: "starters",
    description: "AU FOUR TANDOOR",
    kind: "item",
    name: "GRILLADES",
    priceCents: null,
    sourceOrder: 13,
  },
  {
    category: "starters",
    description: "PIÈCE DE POULET TIKKA, TANDOORI ET AGNEAU TIKKA",
    kind: "variant",
    name: "MIXTE TANDOORI (POUR 2 PERSONNES)",
    priceCents: 1800,
    sourceOrder: 14,
  },
  {
    category: "starters",
    description: "CUISSE DE POULET MARINÉE",
    kind: "variant",
    name: "POULET TANDORI",
    priceCents: 650,
    sourceOrder: 15,
  },
  {
    category: "starters",
    description: "GAMBAS MARINÉS",
    kind: "variant",
    name: "GAMBAS TANDOORI - 5P",
    priceCents: 1500,
    sourceOrder: 16,
  },
  {
    category: "starters",
    description: "BLANC DE POULET MARINÉ",
    kind: "variant",
    name: "POULET TIKKA",
    priceCents: 900,
    sourceOrder: 17,
  },
  {
    category: "starters",
    description: "AGNEAU MARINÉ",
    kind: "variant",
    name: "AGNEAU TIKKA",
    priceCents: 990,
    sourceOrder: 18,
  },
  {
    category: "starters",
    description: "SAUMON MARINÉ",
    kind: "variant",
    name: "SAUMON TIKKA",
    priceCents: 990,
    sourceOrder: 19,
  },
  {
    category: "starters",
    description: "BROCHETTES DE FROMAGE INDIEN AVEC DES LÉGUMES",
    kind: "variant",
    name: "PANEER TIKKA",
    priceCents: 750,
    sourceOrder: 20,
  },
  {
    category: "starters",
    description: "SALADE INDIENNE FAIT MAISON",
    kind: "item",
    name: "LES SALADES",
    priceCents: null,
    sourceOrder: 21,
  },
  {
    category: "starters",
    description:
      "SALADE, OIGNONS, TOMATES, MAÏS OLIVES, POULET TIKKA AVEC NAAN NATURE",
    kind: "variant",
    name: "SALADE POULET TIKKA",
    priceCents: 1300,
    sourceOrder: 22,
  },
  {
    category: "starters",
    description:
      "SALADE, OIGNONS, TOMATES, MAÏS, OLIVES, SAUMON TIKKA AVEC NAAN NATURE",
    kind: "variant",
    name: "SALADE SAUMON TIKKA",
    priceCents: 1500,
    sourceOrder: 23,
  },
  {
    category: "starters",
    description:
      "SALADE, CONCOMBRES, MAÎS, OLIVES, POMMES DE TERRE AVEC NAAN NATURE",
    kind: "variant",
    name: "SALADE VÉGÉTARIENNE",
    priceCents: 1200,
    sourceOrder: 24,
  },
  {
    category: "starters",
    description: "CAROTTES, CONCOMBRES, TOMATES, YAOURT, OIGNONS",
    kind: "variant",
    name: "RAITA",
    priceCents: 500,
    sourceOrder: 25,
  },
  {
    category: "vegetarian-dishes",
    description: "SAUCE À BASE DE LÉGUMES FRAIS SERVIE SANS ACCOMPAGNEMENT",
    kind: "item",
    name: "SAUCE LÉGUMES",
    priceCents: null,
    sourceOrder: 0,
  },
  {
    category: "vegetarian-dishes",
    description: "",
    kind: "variant",
    name: "KOUROUMA",
    priceCents: 800,
    sourceOrder: 1,
  },
  {
    category: "vegetarian-dishes",
    description: "",
    kind: "variant",
    name: "CURRY",
    priceCents: 800,
    sourceOrder: 2,
  },
  {
    category: "vegetarian-dishes",
    description: "",
    kind: "variant",
    name: "VINDALOO",
    priceCents: 800,
    sourceOrder: 3,
  },
  {
    category: "vegetarian-dishes",
    description: "SAUCE AUX LENTILLES SERVIE AVEC RIZ",
    kind: "item",
    name: "DAL",
    priceCents: 1000,
    sourceOrder: 4,
  },
  {
    category: "vegetarian-dishes",
    description:
      "SAUCE AUX LENTILLES AVEC DES MORCEAUX DE FROMAGE INDIEN PANEER TIKKA SERVI AVEC NAAN NATURE",
    kind: "item",
    name: "DAL AU PANEER TIKKA",
    priceCents: 1200,
    sourceOrder: 5,
  },
  {
    category: "vegetarian-dishes",
    description: "5 LÉGUMES EN SAUCE ACCOMPAGNÉS DE RIZ BASMATI",
    kind: "item",
    name: "THALI",
    priceCents: 1300,
    sourceOrder: 6,
  },
  {
    category: "vegetarian-dishes",
    description:
      "MÉLANGE DE RIZ SAFRANÉ, DE TOMATES, D'OIGNONS AU GINGEMBRE, ÉPICES INDIENNES ET FROMAGE INDIEN",
    kind: "item",
    name: "PANEER BUTTER MASALA",
    priceCents: 1200,
    sourceOrder: 7,
  },
  {
    category: "vegetarian-dishes",
    description: "ÉPINARDS AVEC DES MORCEAUX DE FROMAGE INDIEN",
    kind: "item",
    name: "PALAK PANEER",
    priceCents: 1100,
    sourceOrder: 8,
  },
  {
    category: "vegetarian-dishes",
    description: "POIS CHICHE RELEVÉ AUX ÉPICES INDIENNES",
    kind: "item",
    name: "CHANNA MASSALA",
    priceCents: 1100,
    sourceOrder: 9,
  },
  {
    category: "vegetarian-dishes",
    description: "GÂTEAU DE RIZ CUIT À LA VAPEUR SERVI AVEC DES SAUCES",
    kind: "item",
    name: "IDLI - 4P",
    priceCents: 1200,
    sourceOrder: 10,
  },
  {
    category: "vegetarian-dishes",
    description: "CRÊPE INDIENNE SALÉE SERVIE AVEC DES SAUCES",
    kind: "item",
    name: "DOSAI",
    priceCents: null,
    sourceOrder: 11,
  },
  {
    category: "vegetarian-dishes",
    description: "CRÊPE INDIENNE CROUSTILLANT",
    kind: "variant",
    name: "DOSAI CROUSTILLANT",
    priceCents: 990,
    sourceOrder: 12,
  },
  {
    category: "vegetarian-dishes",
    description: "GARNIS AUX POMMES DE TERRE",
    kind: "variant",
    name: "MASSALA DOSAI",
    priceCents: 1200,
    sourceOrder: 13,
  },
  {
    category: "vegetarian-dishes",
    description: "CRÊPE INDIENNE SANS ACCOMPAGNEMENT",
    kind: "variant",
    name: "SUPPLÉMENT DOSAI NATURE",
    priceCents: 500,
    sourceOrder: 14,
  },
  {
    category: "vegetarian-dishes",
    description: "CRÊPE INDIENNE SALÉE SERVIE AVEC DES SAUCES",
    kind: "item",
    name: "DOSAI NON VÉGÉTARIEN",
    priceCents: null,
    sourceOrder: 15,
  },
  {
    category: "vegetarian-dishes",
    description: "OEUFS, VIANDE HACHÉE ET POMME DE TERRE",
    kind: "variant",
    name: "ROYAL DOSAI",
    priceCents: 1400,
    sourceOrder: 16,
  },
  {
    category: "vegetarian-dishes",
    description: "POMMES DE TERRE, OIGNONS CHAMPIGNONS ET POULET",
    kind: "variant",
    name: "BOLLYWOOD DOSAI",
    priceCents: 1400,
    sourceOrder: 17,
  },
  {
    category: "main-courses",
    description:
      "SAUCE COMPOSÉE D'ÉPICES, PIMENTÉE POUR LES AMATEURS DE SENSATIONS FORTES SERVIE SANS ACCOMPAGNEMENT",
    kind: "item",
    name: "SAUCE VINDALOO",
    priceCents: null,
    sourceOrder: 0,
  },
  {
    category: "main-courses",
    description: "",
    kind: "variant",
    name: "POULET",
    priceCents: 1100,
    sourceOrder: 1,
  },
  {
    category: "main-courses",
    description: "",
    kind: "variant",
    name: "AGNEAU",
    priceCents: 1300,
    sourceOrder: 2,
  },
  {
    category: "main-courses",
    description: "",
    kind: "variant",
    name: "CREVETTES",
    priceCents: 1300,
    sourceOrder: 3,
  },
  {
    category: "main-courses",
    description: "",
    kind: "variant",
    name: "GAMBAS",
    priceCents: 1500,
    sourceOrder: 4,
  },
  {
    category: "main-courses",
    description: "",
    kind: "variant",
    name: "SAUMON",
    priceCents: 1400,
    sourceOrder: 5,
  },
  {
    category: "main-courses",
    description:
      "SAUCE PARFUMÉE D'ÉPICES TRADITIONNELLES AU GOÛT ENVOUTANT D'INDE SERVIE SANS ACCOMPAGNEMENT",
    kind: "item",
    name: "SAUCE CURRY",
    priceCents: null,
    sourceOrder: 6,
  },
  {
    category: "main-courses",
    description: "",
    kind: "variant",
    name: "POULET",
    priceCents: 1100,
    sourceOrder: 7,
  },
  {
    category: "main-courses",
    description: "",
    kind: "variant",
    name: "AGNEAU",
    priceCents: 1300,
    sourceOrder: 8,
  },
  {
    category: "main-courses",
    description: "",
    kind: "variant",
    name: "CREVETTES",
    priceCents: 1300,
    sourceOrder: 9,
  },
  {
    category: "main-courses",
    description: "",
    kind: "variant",
    name: "GAMBAS",
    priceCents: 1500,
    sourceOrder: 10,
  },
  {
    category: "main-courses",
    description: "",
    kind: "variant",
    name: "SAUMON",
    priceCents: 1400,
    sourceOrder: 11,
  },
  {
    category: "main-courses",
    description:
      "SAUCE COMPOSÉE D'ÉPICES DOUCES ET PARFUMÉE AU LAIT DE COCO SERVIE SANS ACCOMPAGNEMENT",
    kind: "item",
    name: "SAUCE KOUROUMA",
    priceCents: null,
    sourceOrder: 12,
  },
  {
    category: "main-courses",
    description: "",
    kind: "variant",
    name: "POULET",
    priceCents: 1200,
    sourceOrder: 13,
  },
  {
    category: "main-courses",
    description: "",
    kind: "variant",
    name: "AGNEAU",
    priceCents: 1400,
    sourceOrder: 14,
  },
  {
    category: "main-courses",
    description: "",
    kind: "variant",
    name: "CREVETTES",
    priceCents: 1400,
    sourceOrder: 15,
  },
  {
    category: "main-courses",
    description: "",
    kind: "variant",
    name: "GAMBAS",
    priceCents: 1600,
    sourceOrder: 16,
  },
  {
    category: "main-courses",
    description: "",
    kind: "variant",
    name: "SAUMON",
    priceCents: 1500,
    sourceOrder: 17,
  },
  {
    category: "main-courses",
    description: "MÉLANGE D'ÉPICES INDIENNES, OIGNONS ET POIVRONS",
    kind: "item",
    name: "TIKKA MASSALA",
    priceCents: null,
    sourceOrder: 18,
  },
  {
    category: "main-courses",
    description: "",
    kind: "variant",
    name: "POULET",
    priceCents: 1450,
    sourceOrder: 19,
  },
  {
    category: "main-courses",
    description: "",
    kind: "variant",
    name: "AGNEAU",
    priceCents: 1500,
    sourceOrder: 20,
  },
  {
    category: "main-courses",
    description: "",
    kind: "variant",
    name: "GAMBAS",
    priceCents: 1700,
    sourceOrder: 21,
  },
  {
    category: "main-courses",
    description: "",
    kind: "variant",
    name: "SAUMON",
    priceCents: 1500,
    sourceOrder: 22,
  },
  {
    category: "main-courses",
    description:
      "MÉLANGE DE RIZ SAFRANÉ, DE TOMATES, D'OIGNONS AUX GINGEMBRE ET ÉPICES INDIENNES",
    kind: "item",
    name: "BIRYANI",
    priceCents: null,
    sourceOrder: 23,
  },
  {
    category: "main-courses",
    description: "",
    kind: "variant",
    name: "POULET",
    priceCents: 1300,
    sourceOrder: 24,
  },
  {
    category: "main-courses",
    description: "",
    kind: "variant",
    name: "AGNEAU",
    priceCents: 1400,
    sourceOrder: 25,
  },
  {
    category: "main-courses",
    description: "",
    kind: "variant",
    name: "CREVETTES",
    priceCents: 1300,
    sourceOrder: 26,
  },
  {
    category: "main-courses",
    description: "",
    kind: "variant",
    name: "GAMBAS",
    priceCents: 1500,
    sourceOrder: 27,
  },
  {
    category: "main-courses",
    description: "",
    kind: "variant",
    name: "LÉGUMES",
    priceCents: 1000,
    sourceOrder: 28,
  },
  {
    category: "main-courses",
    description: "EMINCÉES DE BAROTTA AVEC OEUF OU VIANDE",
    kind: "item",
    name: "KOTTU",
    priceCents: null,
    sourceOrder: 29,
  },
  {
    category: "main-courses",
    description: "",
    kind: "variant",
    name: "AGNEAU",
    priceCents: 1200,
    sourceOrder: 30,
  },
  {
    category: "main-courses",
    description: "",
    kind: "variant",
    name: "BOEUF",
    priceCents: 1200,
    sourceOrder: 31,
  },
  {
    category: "main-courses",
    description: "",
    kind: "variant",
    name: "OEUFS",
    priceCents: 1000,
    sourceOrder: 32,
  },
  {
    category: "main-courses",
    description: "",
    kind: "variant",
    name: "POULET",
    priceCents: 1200,
    sourceOrder: 33,
  },
  {
    category: "main-courses",
    description: "",
    kind: "variant",
    name: "LÉGUMES",
    priceCents: 1000,
    sourceOrder: 34,
  },
  {
    category: "specialties",
    description: "POULET AU BEURRE ET RIZ BASMATI",
    kind: "item",
    name: "BUTTER CHICKEN",
    priceCents: 1490,
    sourceOrder: 0,
  },
  {
    category: "specialties",
    description: "CURRY D'AGNEAU ET RIZ BASMATI",
    kind: "item",
    name: "CURRY D'AGNEAU AUX ÉPINARDS",
    priceCents: 1590,
    sourceOrder: 1,
  },
  {
    category: "specialties",
    description: "RIZ SAUTÉ AVEC POULET ET LÉGUMES",
    kind: "item",
    name: "FRIED RICE POULET",
    priceCents: 1450,
    sourceOrder: 2,
  },
  {
    category: "specialties",
    description: "RIZ SAUTÉ AVEC CREVETTES ET GAMBAS ÉPICÉ",
    kind: "item",
    name: "FRIED RICE ROYAL",
    priceCents: 1690,
    sourceOrder: 3,
  },
  {
    category: "specialties",
    description: "POULET FRIT ET épicé",
    kind: "item",
    name: "CHICKEN 65",
    priceCents: 900,
    sourceOrder: 4,
  },
  {
    category: "specialties",
    description: "POULET FRIT POIVRONS ÉPICÉ, SAUCE CHILI",
    kind: "item",
    name: "CHILI CHICKEN",
    priceCents: 1190,
    sourceOrder: 5,
  },
  {
    category: "specialties",
    description: "CREVETTES POIVRONS ÉPICÉES, SAUCE CHILI",
    kind: "item",
    name: "CHILI CREVETTES",
    priceCents: 1490,
    sourceOrder: 6,
  },
  {
    category: "specialties",
    description: "BOEUF SAUTÉ AUX ÉPICES",
    kind: "item",
    name: "BEEF DEVAL",
    priceCents: 1600,
    sourceOrder: 7,
  },
  {
    category: "specialties",
    description:
      "POISSON MARINÉ AUX ÉPICES, GRILLÉ AU FOUR TANDOOR SERVI AVEC DU RIZ",
    kind: "item",
    name: "DORADE ROYALE ENTIÈRE",
    priceCents: 2190,
    sourceOrder: 8,
  },
  {
    category: "specialties",
    description: "",
    kind: "item",
    name: "GARNITURES ET ACCOMPAGNEMENTS",
    priceCents: null,
    sourceOrder: 9,
  },
  {
    category: "specialties",
    description: "",
    kind: "variant",
    name: "NAAN AU FROMAGE",
    priceCents: 400,
    sourceOrder: 10,
  },
  {
    category: "specialties",
    description: "",
    kind: "variant",
    name: "NAAN NATURE",
    priceCents: 300,
    sourceOrder: 11,
  },
  {
    category: "specialties",
    description: "",
    kind: "variant",
    name: "NAAN À L’AIL",
    priceCents: 350,
    sourceOrder: 12,
  },
  {
    category: "specialties",
    description: "",
    kind: "variant",
    name: "KEEMA NAAN",
    priceCents: 550,
    sourceOrder: 13,
  },
  {
    category: "specialties",
    description: "",
    kind: "variant",
    name: "BAROTTHA",
    priceCents: 200,
    sourceOrder: 14,
  },
  {
    category: "specialties",
    description: "",
    kind: "variant",
    name: "CHAPATTY",
    priceCents: 200,
    sourceOrder: 15,
  },
  {
    category: "specialties",
    description: "",
    kind: "variant",
    name: "RIZ BASMATI NATURE",
    priceCents: 350,
    sourceOrder: 16,
  },
  {
    category: "specialties",
    description: "",
    kind: "variant",
    name: "RIZ SUPREME",
    priceCents: 450,
    sourceOrder: 17,
  },
  {
    category: "specialties",
    description: "",
    kind: "variant",
    name: "RIZ COCO",
    priceCents: 550,
    sourceOrder: 18,
  },
  {
    category: "specialties",
    description: "",
    kind: "variant",
    name: "FRITES",
    priceCents: 450,
    sourceOrder: 19,
  },
  {
    category: "desserts",
    description: "GÂTEAU DE SEMOULE AUX NOIX DE CAJOU & RAISINS SECS",
    kind: "item",
    name: "KESARI",
    priceCents: 400,
    sourceOrder: 0,
  },
  {
    category: "desserts",
    description: "BOULETTE DE PÂTE D'AMANDE DANS UN SIROP DE CARDAMONE",
    kind: "item",
    name: "GULAB JAMOUNE",
    priceCents: 450,
    sourceOrder: 1,
  },
  {
    category: "desserts",
    description: "GLACE À L'INDIENNE À LA MANGUE OU À LA PISTACHE",
    kind: "item",
    name: "KULFI",
    priceCents: 450,
    sourceOrder: 2,
  },
  {
    category: "desserts",
    description: "BILLES DE TAPIOCA, LAIT DE COCO & NOIX DE CAJOU",
    kind: "item",
    name: "PAYASAM",
    priceCents: 400,
    sourceOrder: 3,
  },
  {
    category: "desserts",
    description:
      "LAIT, SIROP DE ROSE, GRAINES DE BASILIC, MORCEAUX DE GÉLATINE, BOULE DE GLACE",
    kind: "item",
    name: "FALOODA",
    priceCents: 700,
    sourceOrder: 4,
  },
  {
    category: "desserts",
    description: "",
    kind: "item",
    name: "CRÊPES",
    priceCents: null,
    sourceOrder: 5,
  },
  {
    category: "desserts",
    description: "",
    kind: "variant",
    name: "NATURE",
    priceCents: 300,
    sourceOrder: 6,
  },
  {
    category: "desserts",
    description: "",
    kind: "variant",
    name: "SUCRE",
    priceCents: 350,
    sourceOrder: 7,
  },
  {
    category: "desserts",
    description: "",
    kind: "variant",
    name: "NUTELLA",
    priceCents: 500,
    sourceOrder: 8,
  },
  {
    category: "desserts",
    description: "",
    kind: "variant",
    name: "NUTELLA BANANE",
    priceCents: 550,
    sourceOrder: 9,
  },
  {
    category: "desserts",
    description: "CŒUR COULANT DE CHOCOLAT, BEURRE, OEUF, FARINE, SUCRE",
    kind: "item",
    name: "FONDANT AU CHOCOLAT",
    priceCents: 550,
    sourceOrder: 10,
  },
  {
    category: "desserts",
    description: "SALADE DE FRUITS FRAIS AVEC DE LA GLACE À LA VANILLE",
    kind: "item",
    name: "COCKTAIL DE FRUITS",
    priceCents: 650,
    sourceOrder: 11,
  },
  {
    category: "desserts",
    description: "",
    kind: "item",
    name: "TIRAMISU",
    priceCents: 690,
    sourceOrder: 12,
  },
  {
    category: "desserts",
    description: "",
    kind: "item",
    name: "THE GOURMAND",
    priceCents: 850,
    sourceOrder: 13,
  },
  {
    category: "desserts",
    description: "",
    kind: "item",
    name: "CAFE GOURMAND",
    priceCents: 790,
    sourceOrder: 14,
  },
  {
    category: "desserts",
    description: "",
    kind: "item",
    name: "BANANA SPLIT",
    priceCents: 790,
    sourceOrder: 15,
  },
  {
    category: "desserts",
    description: "",
    kind: "item",
    name: "CHOCOLAT LIEGOIS",
    priceCents: 790,
    sourceOrder: 16,
  },
  {
    category: "desserts",
    description: "",
    kind: "item",
    name: "DAME BLANCHE",
    priceCents: 790,
    sourceOrder: 17,
  },
  {
    category: "desserts",
    description: "",
    kind: "item",
    name: "MANGO COCO",
    priceCents: 790,
    sourceOrder: 18,
  },
  {
    category: "desserts",
    description:
      "BOULE DE GLACE AU CHOIX: VANILLE, CHOCOLAT, MANGUE, COCO, CAFÉ, PISTACHE OU FRAISE",
    kind: "item",
    name: "COUPE DE GLACE",
    priceCents: null,
    sourceOrder: 19,
  },
  {
    category: "desserts",
    description: "",
    kind: "variant",
    name: "1 BOULE",
    priceCents: 300,
    sourceOrder: 20,
  },
  {
    category: "desserts",
    description: "",
    kind: "variant",
    name: "2 BOULES",
    priceCents: 500,
    sourceOrder: 21,
  },
  {
    category: "desserts",
    description: "",
    kind: "item",
    name: "DAME BLANCHE",
    priceCents: 790,
    sourceOrder: 22,
  },
  {
    category: "desserts",
    description: "",
    kind: "item",
    name: "BANANA SPLIT",
    priceCents: 790,
    sourceOrder: 23,
  },
  {
    category: "desserts",
    description: "",
    kind: "item",
    name: "MILKSHAKE",
    priceCents: 600,
    sourceOrder: 24,
  },
  {
    category: "drinks",
    description: "",
    kind: "item",
    name: "EAUX ET SOFT",
    priceCents: null,
    sourceOrder: 0,
  },
  {
    category: "drinks",
    description: "",
    kind: "variant",
    name: "Coca cola/coca zéro (33cl)",
    priceCents: 390,
    sourceOrder: 1,
  },
  {
    category: "drinks",
    description: "",
    kind: "variant",
    name: "Orangina (25cl)",
    priceCents: 390,
    sourceOrder: 2,
  },
  {
    category: "drinks",
    description: "",
    kind: "variant",
    name: "Schweppes (33cl)",
    priceCents: 390,
    sourceOrder: 3,
  },
  {
    category: "drinks",
    description: "",
    kind: "variant",
    name: "Sprite (33cl)",
    priceCents: 390,
    sourceOrder: 4,
  },
  {
    category: "drinks",
    description: "",
    kind: "variant",
    name: "Diablo (25cl)",
    priceCents: 350,
    sourceOrder: 5,
  },
  {
    category: "drinks",
    description: "(Orange, mangue, ananas, pomme, ananas, fraise, abricot)",
    kind: "variant",
    name: "Jus de fruit (25cl)",
    priceCents: 400,
    sourceOrder: 6,
  },
  {
    category: "drinks",
    description: "(Mangue, banane, pistache, Coco ou rose)",
    kind: "variant",
    name: "Lassy",
    priceCents: 550,
    sourceOrder: 7,
  },
  {
    category: "drinks",
    description: "(Lait rose)",
    kind: "variant",
    name: "Rose milk",
    priceCents: 400,
    sourceOrder: 8,
  },
  {
    category: "drinks",
    description: "",
    kind: "variant",
    name: "Vittel (50cl)",
    priceCents: 350,
    sourceOrder: 9,
  },
  {
    category: "drinks",
    description: "",
    kind: "variant",
    name: "Vittel (1L)",
    priceCents: 600,
    sourceOrder: 10,
  },
  {
    category: "drinks",
    description: "",
    kind: "variant",
    name: "San pellegrino (50cl)",
    priceCents: 350,
    sourceOrder: 11,
  },
  {
    category: "drinks",
    description: "",
    kind: "variant",
    name: "San pellegrino (1L)",
    priceCents: 600,
    sourceOrder: 12,
  },
  {
    category: "drinks",
    description: "",
    kind: "item",
    name: "COCKTAILS SANS ALCOOL",
    priceCents: null,
    sourceOrder: 13,
  },
  {
    category: "drinks",
    description: "(Feuille de menthe, citron, sucre et glace pilée)",
    kind: "variant",
    name: "Virgin Mojito",
    priceCents: 690,
    sourceOrder: 14,
  },
  {
    category: "drinks",
    description: "(Jus d'ananas, crème de coco)",
    kind: "variant",
    name: "Pinacolada",
    priceCents: 690,
    sourceOrder: 15,
  },
  {
    category: "drinks",
    description: "(Jus d'ananas, Liqueur de pêche, jus de cranberry)",
    kind: "variant",
    name: "Sex on the beach",
    priceCents: 690,
    sourceOrder: 16,
  },
  {
    category: "drinks",
    description: "(Jus de litchi, goyave, framboise, citron vert, tonic)",
    kind: "variant",
    name: "Grenade",
    priceCents: 690,
    sourceOrder: 17,
  },
  {
    category: "drinks",
    description: "",
    kind: "item",
    name: "SODA SRI-LANKAIS",
    priceCents: null,
    sourceOrder: 18,
  },
  {
    category: "drinks",
    description: "",
    kind: "variant",
    name: "Necto",
    priceCents: 350,
    sourceOrder: 19,
  },
  {
    category: "drinks",
    description: "",
    kind: "variant",
    name: "Orange Barley",
    priceCents: 350,
    sourceOrder: 20,
  },
  {
    category: "drinks",
    description: "",
    kind: "item",
    name: "COCKTAIL AVEC ALCOOL",
    priceCents: null,
    sourceOrder: 21,
  },
  {
    category: "drinks",
    description:
      "(Rhum, citron, menthe, eau pétillante, sirop de sucre de canne, jus de pomme)",
    kind: "variant",
    name: "Mojito",
    priceCents: 890,
    sourceOrder: 22,
  },
  {
    category: "drinks",
    description: "(Rhum, jus d’ananas, crème de coco)",
    kind: "variant",
    name: "Pina colada",
    priceCents: 890,
    sourceOrder: 23,
  },
  {
    category: "drinks",
    description: "(tequila, jus d’orange, sirop de grenadine)",
    kind: "variant",
    name: "Tequila sun rise",
    priceCents: 890,
    sourceOrder: 24,
  },
  {
    category: "drinks",
    description: "(vodka, curaçao, citron)",
    kind: "variant",
    name: "Blue lagon",
    priceCents: 890,
    sourceOrder: 25,
  },
  {
    category: "drinks",
    description: "(vodka, cointreau, jus cranberry, citron)",
    kind: "variant",
    name: "Cosmopolitan",
    priceCents: 890,
    sourceOrder: 26,
  },
  {
    category: "drinks",
    description: "(tequila, Cointreau, citron)",
    kind: "variant",
    name: "Margarita",
    priceCents: 890,
    sourceOrder: 27,
  },
  {
    category: "drinks",
    description: "(rhum, sirop de sucre de canne, sucre de canne, citron)",
    kind: "variant",
    name: "Ti punch",
    priceCents: 890,
    sourceOrder: 28,
  },
  {
    category: "drinks",
    description: "(vodka, jus d'ananas, jus de cranberry, liqueur de pêche)",
    kind: "variant",
    name: "Sex on the beach",
    priceCents: 890,
    sourceOrder: 29,
  },
  {
    category: "drinks",
    description: "(Whisky, café, crème chantilly, sirop de sucre)",
    kind: "variant",
    name: "Irish Coffee",
    priceCents: 890,
    sourceOrder: 30,
  },
  {
    category: "drinks",
    description: "(Bière blanche, Limonade et grenadine)",
    kind: "variant",
    name: "Monaco",
    priceCents: 890,
    sourceOrder: 31,
  },
  {
    category: "drinks",
    description: "",
    kind: "item",
    name: "BOISSONS CHAUDES",
    priceCents: null,
    sourceOrder: 32,
  },
  {
    category: "drinks",
    description: "(Thé au lait massala)",
    kind: "variant",
    name: "Chai",
    priceCents: 400,
    sourceOrder: 33,
  },
  {
    category: "drinks",
    description: "",
    kind: "variant",
    name: "Thé Massala",
    priceCents: 450,
    sourceOrder: 34,
  },
  {
    category: "drinks",
    description: "",
    kind: "variant",
    name: "Thé ceylon",
    priceCents: 400,
    sourceOrder: 35,
  },
  {
    category: "drinks",
    description: "(Fruit rouge,earl grey,vanille caramel)",
    kind: "variant",
    name: "Thé Richard",
    priceCents: 400,
    sourceOrder: 36,
  },
  {
    category: "drinks",
    description: "",
    kind: "variant",
    name: "Café",
    priceCents: 220,
    sourceOrder: 37,
  },
  {
    category: "drinks",
    description: "",
    kind: "variant",
    name: "Café crème",
    priceCents: 400,
    sourceOrder: 38,
  },
  {
    category: "drinks",
    description: "",
    kind: "variant",
    name: "Chocolat chaud",
    priceCents: 400,
    sourceOrder: 39,
  },
  {
    category: "drinks",
    description: "(café traditionnel aux épices du Sri-lanka)",
    kind: "variant",
    name: "Ceylon coffee",
    priceCents: 250,
    sourceOrder: 40,
  },
  {
    category: "drinks",
    description: "",
    kind: "item",
    name: "Apéritifs",
    priceCents: null,
    sourceOrder: 41,
  },
  {
    category: "drinks",
    description: "(2cl)",
    kind: "variant",
    name: "Ricard",
    priceCents: 450,
    sourceOrder: 42,
  },
  {
    category: "drinks",
    description: "(12cl)",
    kind: "variant",
    name: "Kir",
    priceCents: 350,
    sourceOrder: 43,
  },
  {
    category: "drinks",
    description: "(12cl)",
    kind: "variant",
    name: "Kir Royal",
    priceCents: 800,
    sourceOrder: 44,
  },
  {
    category: "drinks",
    description: "(2cl)",
    kind: "variant",
    name: "Gin Tonic",
    priceCents: 550,
    sourceOrder: 45,
  },
  {
    category: "drinks",
    description: "(4cl)",
    kind: "variant",
    name: "Rhum",
    priceCents: 650,
    sourceOrder: 46,
  },
  {
    category: "drinks",
    description: "(4cl)",
    kind: "variant",
    name: "Balantines",
    priceCents: 700,
    sourceOrder: 47,
  },
  {
    category: "drinks",
    description: "",
    kind: "variant",
    name: "Jack Daniel",
    priceCents: 800,
    sourceOrder: 48,
  },
  {
    category: "drinks",
    description: "",
    kind: "variant",
    name: "Belvedere",
    priceCents: 800,
    sourceOrder: 49,
  },
  {
    category: "drinks",
    description: "",
    kind: "variant",
    name: "Ciroc",
    priceCents: 900,
    sourceOrder: 50,
  },
  {
    category: "drinks",
    description: "(12cl)",
    kind: "variant",
    name: "Coupe de champagne",
    priceCents: 900,
    sourceOrder: 51,
  },
  {
    category: "drinks",
    description: "(4cl)",
    kind: "variant",
    name: "Martini",
    priceCents: 550,
    sourceOrder: 52,
  },
  {
    category: "drinks",
    description: "(4cl)",
    kind: "variant",
    name: "Martini blanco",
    priceCents: 450,
    sourceOrder: 53,
  },
  {
    category: "drinks",
    description: "",
    kind: "variant",
    name: "Porto",
    priceCents: 550,
    sourceOrder: 54,
  },
  {
    category: "drinks",
    description: "",
    kind: "item",
    name: "les bières",
    priceCents: null,
    sourceOrder: 55,
  },
  {
    category: "drinks",
    description: "",
    kind: "variant",
    name: "King Fisher (33cl)",
    priceCents: 500,
    sourceOrder: 56,
  },
  {
    category: "drinks",
    description: "",
    kind: "variant",
    name: "Lion stout ou lager (33cl)",
    priceCents: 550,
    sourceOrder: 57,
  },
  {
    category: "drinks",
    description: "",
    kind: "variant",
    name: "Lion stout ou lager (62,5cl)",
    priceCents: 950,
    sourceOrder: 58,
  },
  {
    category: "drinks",
    description: "",
    kind: "variant",
    name: "Heineken",
    priceCents: 450,
    sourceOrder: 59,
  },
  {
    category: "drinks",
    description: "",
    kind: "variant",
    name: "Desperatos",
    priceCents: 500,
    sourceOrder: 60,
  },
  {
    category: "drinks",
    description: "",
    kind: "variant",
    name: "Kronenbourg 1664",
    priceCents: 450,
    sourceOrder: 61,
  },
  {
    category: "drinks",
    description: "",
    kind: "item",
    name: "LES CHAMPAGNES (75cl)",
    priceCents: null,
    sourceOrder: 62,
  },
  {
    category: "drinks",
    description: "",
    kind: "variant",
    name: "Nicolas feuillatte",
    priceCents: 4700,
    sourceOrder: 63,
  },
  {
    category: "drinks",
    description: "",
    kind: "variant",
    name: "Moet et chandon",
    priceCents: 7900,
    sourceOrder: 64,
  },
  {
    category: "drinks",
    description: "(blanc de blanc)",
    kind: "variant",
    name: "Ruinart",
    priceCents: 12_000,
    sourceOrder: 65,
  },
  {
    category: "drinks",
    description: "",
    kind: "variant",
    name: "Ruinart Rosé",
    priceCents: 15_000,
    sourceOrder: 66,
  },
  {
    category: "wines",
    description: "",
    kind: "item",
    name: "VINS ROSE (75cl)",
    priceCents: null,
    sourceOrder: 0,
  },
  {
    category: "wines",
    description: "(Aoc Prieure Montezague)",
    kind: "variant",
    name: "Tavel",
    priceCents: 2400,
    sourceOrder: 1,
  },
  {
    category: "wines",
    description: "",
    kind: "variant",
    name: "Saint-Barthélémy IGP Var",
    priceCents: 2000,
    sourceOrder: 2,
  },
  {
    category: "wines",
    description: "(Romain Desbastides)",
    kind: "variant",
    name: "Côtes de provence",
    priceCents: 2700,
    sourceOrder: 3,
  },
  {
    category: "wines",
    description: "",
    kind: "item",
    name: "VINS BLANC (75cl)",
    priceCents: null,
    sourceOrder: 4,
  },
  {
    category: "wines",
    description: "(château de la Mouchetière)",
    kind: "variant",
    name: "Muscadet-Sevre et Maine AOC",
    priceCents: 1650,
    sourceOrder: 5,
  },
  {
    category: "wines",
    description: "(Alsace Hans Schaeffer)",
    kind: "variant",
    name: "Riesling AC",
    priceCents: 2400,
    sourceOrder: 6,
  },
  {
    category: "wines",
    description: "(Les Broux)",
    kind: "variant",
    name: "Sancerre AOC",
    priceCents: 3500,
    sourceOrder: 7,
  },
  {
    category: "wines",
    description: "",
    kind: "item",
    name: "VINS ROUGE (75cl)",
    priceCents: null,
    sourceOrder: 8,
  },
  {
    category: "wines",
    description: "(Chapelle De Barbe)",
    kind: "variant",
    name: "Bordeaux Supérieur AOC",
    priceCents: 1800,
    sourceOrder: 9,
  },
  {
    category: "wines",
    description: "(Beaujolais)",
    kind: "variant",
    name: "Brouilly Beauvoisie AOC",
    priceCents: 2400,
    sourceOrder: 10,
  },
  {
    category: "wines",
    description: "(Pure Garrigue Honore Laubanel)",
    kind: "variant",
    name: "Côtes du rhone AC",
    priceCents: 1950,
    sourceOrder: 11,
  },
  {
    category: "wines",
    description: "(Château le Bourdieu Vertheuil)",
    kind: "variant",
    name: "Haut Medoc AOC",
    priceCents: 3000,
    sourceOrder: 12,
  },
  {
    category: "wines",
    description: "",
    kind: "item",
    name: "LES VINS EN PICHET",
    priceCents: null,
    sourceOrder: 13,
  },
  {
    category: "wines",
    description: "(25cl)",
    kind: "variant",
    name: "Pichet de vin rouge",
    priceCents: 650,
    sourceOrder: 14,
  },
  {
    category: "wines",
    description: "(50cl)",
    kind: "variant",
    name: "Pichet de vin rouge",
    priceCents: 1000,
    sourceOrder: 15,
  },
  {
    category: "wines",
    description: "(25cl)",
    kind: "variant",
    name: "Pichet de vin rose",
    priceCents: 600,
    sourceOrder: 16,
  },
  {
    category: "wines",
    description: "(50cl)",
    kind: "variant",
    name: "Pichet de vin rose",
    priceCents: 1000,
    sourceOrder: 17,
  },
  {
    category: "wines",
    description: "(25cl)",
    kind: "variant",
    name: "Pichet de vin blanc",
    priceCents: 600,
    sourceOrder: 18,
  },
  {
    category: "wines",
    description: "(50cl)",
    kind: "variant",
    name: "Pichet de vin blanc",
    priceCents: 1000,
    sourceOrder: 19,
  },
  {
    category: "wines",
    description: "",
    kind: "item",
    name: "LES VINS EN VERRE (14cl)",
    priceCents: null,
    sourceOrder: 20,
  },
  {
    category: "wines",
    description: "",
    kind: "variant",
    name: "Vin Rouge - Richarg Vin et Domaine",
    priceCents: 400,
    sourceOrder: 21,
  },
  {
    category: "wines",
    description: "",
    kind: "variant",
    name: "Vin Rose - Richarg Vin et Domaine",
    priceCents: 500,
    sourceOrder: 22,
  },
  {
    category: "wines",
    description: "",
    kind: "variant",
    name: "Vin Blanc - Richarg Vin et Domaine",
    priceCents: 400,
    sourceOrder: 23,
  },
] as const;
