// Auto-generated by Furin. Do not edit manually.
/// <reference types="@teyik0/furin/env" />
import "@teyik0/furin/link";

declare module "@teyik0/furin/link" {
  interface RouteManifest {
    "/": { search?: never; searchInput?: never };
    [key: `/${string}`]: { search?: never; searchInput?: never };
    "/contact": { search?: never; searchInput?: never };
    "/gallery": { search?: never; searchInput?: never };
    "/menu": { search?: never; searchInput?: never };
    [key: `/menu/${string}`]: { search?: never; searchInput?: never };
    "/privacy": { search?: never; searchInput?: never };
  }
}

declare module "@teyik0/furin" {
  interface FurinCacheTags {
    content: 'content';
    gallery: 'gallery';
    menu: 'menu';
  }
}
